### ISSUE TITLE
Read me updates

### ISSUE THREAD

**Issue by davidrenne** [wildfish/cookiecutter-django-crud#8]
Can you add:

pip install django-vanilla-views; pip install model_mommy;pip install django_webtest;pip install django-bootstrap3;

to a list of installed dependencies?

**Comment by rolo** [comment]
Hiya. This should be covered by this step in the REAMDE:

`pip install -r https://raw.github.com/wildfish/cookiecutter-django-crud/master/requirements.txt`

Did you try that, or do you just mean it could be clearer?

Thanks

**Comment by davidrenne** [comment]
No I must have skipped passed that on accident.



—
Dave

**Comment by rolo** [comment]
Ah cool. Will close.
